server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000
  port: 8082
  servlet:
    context-path:

grpc:
    port: 8882
    certPath: C:\treeke\ideWorkspace\treeke-grpc\grpc-server\src\main\resources\ca.cer
    keyPath: C:\treeke\ideWorkspace\treeke-grpc\grpc-server\src\main\resources\ca.key
