server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000
  port: 8081
  servlet:
    context-path:

grpc:
    port: 8881
    certPath: C:\treeke\ideWorkspace\treeke-grpc\grpc-client\src\main\resources\server.cer
    keyPath: C:\treeke\ideWorkspace\treeke-grpc\grpc-client\src\main\resources\server.key
